//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyANDTastyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal
    {
        public int mealID { get; set; }
        public string Mname { get; set; }
        public double price { get; set; }
        public string ingrdiants { get; set; }
        public string type { get; set; }
        public int DietID { get; set; }
        public byte[] image { get; set; }
    
        public virtual Diet Diet { get; set; }
    }
}
