//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyANDTastyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int mealID { get; set; }
        public string state { get; set; }
        public string comment { get; set; }
    
        public virtual Bell Bell { get; set; }
        public virtual User User { get; set; }
    }
}
