//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyANDTastyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int customerID { get; set; }
        public string fullName { get; set; }
        public Nullable<int> age { get; set; }
        public string address { get; set; }
        public string e_mail { get; set; }
        public string phone { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> hight { get; set; }
        public string medicalState { get; set; }
        public Nullable<int> FreePoints { get; set; }
        public Nullable<decimal> creditLimit { get; set; }
        public int DietID { get; set; }
        public Nullable<int> free_meals { get; set; }
        public string password { get; set; }
    
        public virtual Diet Diet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
