//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyAndTestyPresentation {
    
    
    public partial class Meanue {
        
        /// <summary>
        /// AdminHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HealthyAndTestyPresentation.UserControls.AdminHeader AdminHeader;
        
        /// <summary>
        /// UserHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HealthyAndTestyPresentation.UserControls.UserHeader UserHeader;
        
        /// <summary>
        /// MenueWebUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HealthyAndTestyPresentation.UserControls.MenueWebUserControl MenueWebUserControl;
        
        /// <summary>
        /// FooterWebUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HealthyAndTestyPresentation.UserControls.WebUserControl1 FooterWebUserControl;
    }
}
